#! /bin/csh -f
#
#=============================================================================
#
# $Id: seabf_word,v 1.2 2011-08-09 22:12:59 mrdamon Exp $
#
# CODE DEVELOPER
#   John Tannahill , LLNL     , jrt@llnl.gov
#   Jules Kouatchou, NASA/GSFC, Jules.Kouatchou-1@nasa.gov
#
# FILE
#   seabf_word
#
# DESCRIPTION
#   This script searches through the ".F90" source files for a
#   particular word (case insensitive).  Output comes to the screen
#   unless an optional second file_name argument is provided.
#
#   Usage:  seabf_word search_string [file_name]
#
#=============================================================================
#


@ err = 0


if ($#argv == 1) then

  (cd $GMIHOME; grep -iw $argv[1] */*.F90 */*/*.F90 */*/*/*.F90 */*/*/*/*.F90 */*/*/*/*/*.F90)

else if ($#argv == 2) then

  (cd $GMIHOME; grep -iw $argv[1] */*.F90 */*/*.F90 */*/*/*.F90 */*/*/*/*.F90 */*/*/*/*/*.F90) >> $argv[2]

else

  echo ""
  echo "Usage:  $0 search_word [file_name]"
  echo ""
  @ err = 1

endif


exit $err

