#! /bin/csh -f
#
#=============================================================================
#
# $Id: seac,v 1.2 2011-08-09 22:12:59 mrdamon Exp $
#
# CODE DEVELOPER
#   John Tannahill , LLNL     , jrt@llnl.gov
#   Jules Kouatchou, NASA/GSFC, Jules.Kouatchou-1@nasa.gov
#
# FILE
#   seac
#
# DESCRIPTION
#   This script searches through the .c source files for a
#   particular string (case insensitive).  Output comes to the screen
#   unless an optional second file_name argument is provided.
#
#   Usage:  seah search_string [file_name]
#
#=============================================================================
#


@ err = 0


if ($#argv == 1) then

  (cd $GMIHOME; grep -i "$argv[1]" */*.c */*/*.c */*/*/*.c)

else if ($#argv == 2) then

  (cd $GMIHOME; grep -i "$argv[1]" */*.c */*/*.c */*/*/*.c) > $argv[2]

else

  echo ""
  echo "Usage:  $0 search_string [file_name]"
  echo ""
  @ err = 1

endif


exit $err

