#! /bin/csh -f
#
#=============================================================================
#
# $Id: sealf,v 1.2 2011-08-09 22:12:59 mrdamon Exp $
#
# CODE DEVELOPER
#   John Tannahill , LLNL     , jrt@llnl.gov
#   Jules Kouatchou, NASA/GSFC, Jules.Kouatchou-1@nasa.gov
#
# FILE
#   sealf
#
# DESCRIPTION
#   This script searches through the ".f90" source files for a
#   particular string (case insensitive).  Output comes to the screen
#   unless an optional second file_name argument is provided.
#
#   Usage:  sealf search_string [file_name]
#
#=============================================================================
#


@ err = 0


if ($#argv == 1) then

  (cd $GMIHOME; grep -i "$argv[1]"  */*.f90  */*/*.f90 */*/*/*.f90 */*/*/*/*.f90 */*/*/*/*/*.f90)

else if ($#argv == 2) then

  (cd $GMIHOME; grep -i "$argv[1]"  */*.f90  */*/*.f90 */*/*/*.f90 */*/*/*/*.f90 */*/*/*/*/*.f90) >> $argv[2]

else

  echo ""
  echo "Usage:  $0 search_string [file_name]"
  echo ""
  @ err = 1

endif


exit $err

