#! /bin/csh -f
#
#=============================================================================
#
# $Id: seamf,v 1.2 2011-08-09 22:12:59 mrdamon Exp $
#
# CODE DEVELOPER
#   John Tannahill , LLNL     , jrt@llnl.gov
#   Jules Kouatchou, NASA/GSFC, Jules.Kouatchou-1@nasa.gov
#
# FILE
#   seamf
#
# DESCRIPTION
#   This script searches through the "Makefile.cpp" and "Makefile" source files
#   for a particular string (case insensitive).  Output comes to the screen
#   unless an optional second file_name argument is provided.
#
#   Usage:  seamf search_string [file_name]
#
#=============================================================================
#


@ err = 0


if ($#argv == 1) then

  find $GMIHOME -name "Makefile.cpp" -print -exec grep -i "$argv[1]" "{}" \;
  find $GMIHOME -name "Makefile"     -print -exec grep -i "$argv[1]" "{}" \;

else if ($#argv == 2) then

  (find $GMIHOME -name "Makefile.cpp" -print -exec grep -i "$argv[1]" "{}" \;) > \
  $argv[2]
  (find $GMIHOME -name "Makefile"     -print -exec grep -i "$argv[1]" "{}" \;) > \
  $argv[2]

else

  echo ""
  echo "Usage:  $0 search_string [file_name]"
  echo ""
  @ err = 1

endif


exit $err

